name: Build Net Core and Angular App 🚀

on:    
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ANGULAR_DIR: ./net-angular-ci/net-angular-ci
  DEPLOY_DIR:  /Users/jcmendez/Documents/learn/azure/net-angular-vm/MyApp
  

jobs:
  build:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v3     

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          include-prerelease: true
           
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # - name: Test DOTNET
      #   run: dotnet test --no-restore --verbosity normal

      - name: Publish DOTNET
        run: dotnet publish -c Release  -o ${{ env.DEPLOY_DIR }}     

      
      ##
      ## NOTE: Next secion is dedicated to angular, it install dependencies, run linters, runs unit test and generate the bundle
      ## uncomment if it is neccesary to run any of this action in a separate way of .net template
      ##

      #- name: Set up node.js
      #  uses: actions/setup-node@v3.3.0
      #  with:
      #    node-version: '12'
      #    cache: 'npm'      

      #- name: Install NPM dependencies
      #  if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      #  working-directory: ${{ env.ANGULAR_DIR }}
      #  run: npm install

      #- name: Run linters and prettier fix
      #  working-directory: ${{ env.ANGULAR_DIR }}
      #  run: npm run lint

      #- name: Run Angular tests
      #  working-directory: ${{ env.ANGULAR_DIR }}
      #  run: npm run test

      #- name: Build Angular App
      #  working-directory: ${{ env.ANGULAR_DIR }}
      #  run: |
      #      npm run build:prod
      #      ls
      #      Copy-Item -Path ./dist/* -Destination ${{ env.DEPLOY_DIR }}ClientApp -Recurse
            

      - name: Upload artifact for deployment job
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.DEPLOY_DIR }}
          retention-days: 10
